name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: node
      id: node
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: node
        setup-command: npm install
        command: npm test
        timeout: 10
    - name: java
      id: java
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: java
        setup-command: ''
        command: gradle test
        timeout: 10
    - name: python
      id: python
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
    - name: c
      id: c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: c
        setup-command: ''
        command: make test
        timeout: 10
    - name: cpp
      id: cpp
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: cpp
        setup-command: ''
        command: make test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        NODE_RESULTS: "${{steps.node.outputs.result}}"
        JAVA_RESULTS: "${{steps.java.outputs.result}}"
        PYTHON_RESULTS: "${{steps.python.outputs.result}}"
        C_RESULTS: "${{steps.c.outputs.result}}"
        CPP_RESULTS: "${{steps.cpp.outputs.result}}"
      with:
        runners: node,java,python,c,cpp
